In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [88]:
df=pd.read_excel(r"C:\Users\KIIT\Desktop\ML\multiple.xlsx")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [100]:
median_bedroom

3

In [89]:
import math
median_bedroom=math.floor(df.bedroom.median())

median_bedroom

3

In [90]:
df.bedroom.fillna(median_bedroom)


0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedroom, dtype: float64

In [91]:
df.bedroom = df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [93]:
#create linear regression class object
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)



LinearRegression()

In [95]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [96]:
reg.intercept_

383724.9999999998

In [98]:
reg.predict([[3000,2,14]])

array([647875.])

In [99]:
reg.predict([[3600,3,30]])

array([595000.])